# Generated by Django 2.1.1 on 2018-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20181003_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
