# Generated by Django 2.1.1 on 2018-10-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_auto_20181003_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name_plural': 'sunscribes'},
        ),
    ]
