# Generated by Django 2.1.1 on 2018-10-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='read',
            options={'verbose_name_plural': 'reads'},
        ),
    ]
