# Generated by Django 2.1.1 on 2018-10-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_auto_20181004_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='articles_readed',
            field=models.ManyToManyField(null=True, related_name='articles_readed', to='articles.Article'),
        ),
    ]
