# Generated by Django 2.1.1 on 2018-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0007_auto_20181004_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
