# Generated by Django 2.1.1 on 2018-09-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
