# Generated by Django 2.1.1 on 2018-10-02 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='subscribers',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
